services:
  - type: web
    name: band-review-website-backend
    env: python
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python init_production_db.py && gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: CORS_ORIGINS
        value: https://bandvenuereview.netlify.app,http://localhost:3000
      - key: DATABASE_URL
        fromDatabase:
          name: bandvenuereview-db
          property: connectionString

databases:
  - name: bandvenuereview-db
    databaseName: bandvenuereview
    user: bandvenuereview
    plan: free
