services:
  - type: web
    name: bandvenuereview-api
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python init_db.py && gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bandvenuereview-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://bandvenuereview.netlify.app,https://*.netlify.app
    healthCheckPath: /api/health

databases:
  - name: bandvenuereview-db
    databaseName: bandvenuereview
    user: bandvenuereview
    plan: free
