/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SoundStudio = {
  _id: string
  _type: 'soundStudio'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  description?: string
  address?: {
    street?: string
    city?: string
    county?:
      | 'Dublin'
      | 'Wicklow'
      | 'Wexford'
      | 'Carlow'
      | 'Kildare'
      | 'Meath'
      | 'Louth'
      | 'Longford'
      | 'Westmeath'
      | 'Offaly'
      | 'Laois'
      | 'Kilkenny'
      | 'Cork'
      | 'Kerry'
      | 'Limerick'
      | 'Tipperary'
      | 'Waterford'
      | 'Clare'
      | 'Galway'
      | 'Mayo'
      | 'Roscommon'
      | 'Sligo'
      | 'Leitrim'
      | 'Donegal'
      | 'Cavan'
      | 'Monaghan'
      | 'Antrim'
      | 'Armagh'
      | 'Down'
      | 'Fermanagh'
      | 'Londonderry'
      | 'Tyrone'
    country?: string
    eircode?: string
  }
  location?: Geopoint
  contact?: {
    phone?: string
    email?: string
    website?: string
    facebook?: string
    instagram?: string
    twitter?: string
  }
  profileImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  gallery?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  amenities?: Array<string>
  pricing?: {
    hourlyRate?: number
    halfDayRate?: number
    fullDayRate?: number
    engineerIncluded?: boolean
    mixingRate?: number
    masteringRate?: number
    currency?: 'EUR' | 'GBP' | 'USD'
  }
  genresSupported?: Array<string>
  bandFriendly?: boolean
  studioType?: 'professional' | 'home' | 'project' | 'commercial' | 'rehearsal_recording' | 'mobile'
  features?: Array<string>
  capacity?: number
  verified?: boolean
  featured?: boolean
  claimed?: boolean
  openingHours?: {
    monday?: string
    tuesday?: string
    wednesday?: string
    thursday?: string
    friday?: string
    saturday?: string
    sunday?: string
  }
}

export type Gig = {
  _id: string
  _type: 'gig'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  venue?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'venue'
  }
  headliner?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'band'
  }
  supportActs?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'band'
  }>
  date?: string
  ticketPrice?: number
  ticketUrl?: string
  description?: string
  poster?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  status?: 'upcoming' | 'sold_out' | 'cancelled' | 'completed'
  genre?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'genre'
  }
  ageRestriction?: 'all_ages' | '16_plus' | '18_plus' | '21_plus'
  featured?: boolean
}

export type Genre = {
  _id: string
  _type: 'genre'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  description?: string
  color?: Color
  parentGenre?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'genre'
  }
}

export type Review = {
  _id: string
  _type: 'review'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  reviewer?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'band'
  }
  venue?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'venue'
  }
  gigDate?: string
  overallRating?: 1 | 2 | 3 | 4 | 5
  ratings?: {
    soundQuality?: number
    hospitality?: number
    payment?: number
    facilities?: number
    audience?: number
  }
  reviewText?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h3' | 'h4' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  photos?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    caption?: string
    alt?: string
    category?:
      | 'stage'
      | 'sound'
      | 'lighting'
      | 'green_room'
      | 'interior'
      | 'audience'
      | 'performance'
      | 'other'
    _type: 'image'
    _key: string
  }>
  gigDetails?: {
    attendance?: number
    supportActs?: Array<string>
    ticketPrice?: number
    paymentAmount?: number
    setDuration?: number
  }
  wouldPlayAgain?: boolean
  recommendToOthers?: boolean
  published?: boolean
  featured?: boolean
  tags?: Array<string>
}

export type Venue = {
  _id: string
  _type: 'venue'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  description?: string
  heroImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  gallery?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    caption?: string
    alt?: string
    _type: 'image'
    _key: string
  }>
  address?: {
    street?: string
    city?: string
    county?:
      | 'Dublin'
      | 'Wicklow'
      | 'Wexford'
      | 'Carlow'
      | 'Kildare'
      | 'Meath'
      | 'Louth'
      | 'Longford'
      | 'Westmeath'
      | 'Offaly'
      | 'Laois'
      | 'Kilkenny'
      | 'Cork'
      | 'Kerry'
      | 'Limerick'
      | 'Tipperary'
      | 'Waterford'
      | 'Clare'
      | 'Galway'
      | 'Mayo'
      | 'Roscommon'
      | 'Sligo'
      | 'Leitrim'
      | 'Donegal'
      | 'Cavan'
      | 'Monaghan'
      | 'Antrim'
      | 'Armagh'
      | 'Down'
      | 'Fermanagh'
      | 'Londonderry'
      | 'Tyrone'
    eircode?: string
    country?: string
  }
  location?: Geopoint
  contact?: {
    phone?: string
    email?: string
    website?: string
  }
  capacity?: number
  venueType?: 'pub' | 'club' | 'theatre' | 'arena' | 'festival_ground' | 'concert_hall' | 'other'
  primaryGenres?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'genre'
  }>
  facilities?: Array<string>
  techSpecs?: {
    soundSystem?: string
    lightingRig?: string
    stageSize?: string
    backline?: Array<string>
  }
  verified?: boolean
  claimed?: boolean
  featured?: boolean
}

export type Band = {
  _id: string
  _type: 'band'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  bio?: string
  profileImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  bannerImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  gallery?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    caption?: string
    alt?: string
    _type: 'image'
    _key: string
  }>
  genres?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'genre'
  }>
  location?: Geopoint
  locationDetails?: {
    city?: string
    county?:
      | 'Dublin'
      | 'Wicklow'
      | 'Wexford'
      | 'Carlow'
      | 'Kildare'
      | 'Meath'
      | 'Louth'
      | 'Longford'
      | 'Westmeath'
      | 'Offaly'
      | 'Laois'
      | 'Kilkenny'
      | 'Cork'
      | 'Kerry'
      | 'Limerick'
      | 'Tipperary'
      | 'Waterford'
      | 'Clare'
      | 'Galway'
      | 'Mayo'
      | 'Roscommon'
      | 'Sligo'
      | 'Leitrim'
      | 'Donegal'
      | 'Cavan'
      | 'Monaghan'
      | 'Antrim'
      | 'Armagh'
      | 'Down'
      | 'Fermanagh'
      | 'Londonderry'
      | 'Tyrone'
    country?: string
  }
  locationText?: string
  formedYear?: number
  socialLinks?: {
    website?: string
    spotify?: string
    youtube?: string
    instagram?: string
    facebook?: string
    twitter?: string
    bandcamp?: string
    soundcloud?: string
  }
  verified?: boolean
  featured?: boolean
  members?: Array<{
    name?: string
    instrument?: string
    photo?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _key: string
  }>
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | SoundStudio
  | Gig
  | Genre
  | Review
  | Venue
  | Band
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
